[tools]
starship = "1.26.0"
ripgrep = "15.2.0"
fd = "10.4.2"
fzf = "0.74.1"
"github:ogulcancelik/herdr" = { version = "0.7.5" }
bat = "0.26.1"
lsd = "1.2.0"
zoxide = "0.10.0"
atuin = "18.17.1"
"cargo:navi" = "2.24.0"
zellij = "0.44.3"
yazi = "26.5.6"
uv = "0.11.32"
prek = "0.4.11"
gh = "2.96.0"
node = "26.5.0"
"npm:@earendil-works/pi-coding-agent" = "0.82.1"
"github:vicinaehq/vicinae" = { version = "0.23.2", os = ["linux"], asset_pattern = "vicinae-linux-x86_64-v{{version}}.tar.gz" }
"cargo:cargo-edit" = "0.13.13"
"cargo:stylua" = "2.5.2"
