[tools]
starship = "1.23.0"
ripgrep = "14.1.1"
fd = "10.2.0"
bat = "0.25.0"
lsd = "1.1.5"
zoxide = "0.9.8"
atuin = "18.17.1"
zellij = "0.41.2"
yazi = "25.5.31"
uv = "0.11.32"
prek = "0.4.11"
gh = "2.96.0"
"cargo:cargo-edit" = "0.13.13"
"cargo:stylua" = "2.5.2"
