[tools]
starship = "1.26.0"
ripgrep = "15.2.0"
fd = "10.4.2"
fzf = "0.74.2"
herdr = "latest"
codex = "latest"
bat = "0.26.1"
lsd = "1.2.0"
zoxide = "0.10.0"
atuin = "18.19.0"
"cargo:navi" = "2.24.0"
yazi = "26.5.6"
neovim = "latest"
uv = "0.12.3"
prek = "0.4.12"
gh = "2.97.0"
node = "26.7.0"
"npm:@earendil-works/pi-coding-agent" = "0.84.1"
"github:vicinaehq/vicinae" = { version = "0.24.0", asset_pattern = "vicinae-linux-x86_64-v{version}.tar.gz", os = ["linux"] }
"cargo:cargo-edit" = "0.13.13"
"cargo:stylua" = "2.5.2"
