[general]
import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[font]
size = 16

[font.normal]
family = "0xProto Nerd Font"

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[cursor.style]
shape = "Underline"
blinking = "On"

[scrolling]
history = 100000

[env]
term = "xterm-256color"

[keyboard]
bindings = [
  { key = "Key1", mods = "Command", chars = "\u001b1" },
  { key = "Key2", mods = "Command", chars = "\u001b2" },
]
