import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[font]
size = 16

[font.normal]
family = "Cascadia Code NF"

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"

[window.padding]
x = 25
y = 25

[scrolling]
history = 100000

[env]
term = "xterm-256color"
