# Per-tag default layout
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile

# Layer rules
layerrule=noanim:1,layer_name:rofi

# Monitor rules
monitorrule=name:DP-1,rr:1,scale:1,x:0,y:0,width:1920,height:1080,refresh:143.854797
monitorrule=name:HDMI-A-1,rr:0,scale:1,x:1920,y:0,width:2560,height:1440,refresh:119.997589
