[package]
disabled = true

[python]
pyenv_version_name = false
disabled = true

[nodejs]
disabled = true

[username]
show_always = false
style_user = "bold #EFA700"

[hostname]
ssh_only = true
style = "bold purple"

[git_branch]
style = "bold yellow"
symbol = '🌱 '
truncation_length = 15
truncation_symbol = ''
ignore_branches = ['master', 'main']

[cmd_duration]
style = "green"

[git_commit]
commit_hash_length = 7
tag_symbol = '🔖 '
only_detached = false
tag_disabled = false
