[package]
disabled = true

[python]
format = 'via [(${version} )(\($virtualenv\) )]($style)'
symbol = ""
style = "bold #f3e10b"

[username]
show_always = false
style_user = "bold #EFA700"

[hostname]
ssh_only = true
style = "bold purple"

[git_branch]
style = "bold yellow"

[cmd_duration]
style = "green"

[memory_usage]
disabled = false
threshold = -1
symbol = ''
style = 'dimmed'
