# Keyboard and pointer input
cursor_size=24
repeat_rate=35
repeat_delay=200
numlockon=0
xkb_rules_layout=us
xkb_rules_options=terminate:ctrl_alt_bksp,caps:escape

disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1

mouse_natural_scrolling=0
