# Colors
rootcolor=0x40515aff
bordercolor=0x33434bff
focuscolor=0x5084cfff
maximizescreencolor=0xf8ae3bff
urgentcolor=0xd95d5dff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff
