name: validate
on: [push, pull_request]
permissions: {contents: read}
jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with: {python-version: '3.12'}
      - run: sudo apt-get update && sudo apt-get install --yes shellcheck shfmt zsh neovim
      - name: Install prek
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/j178/prek/releases/latest/download/prek-installer.sh | sh
      - run: prek run --all-files
      - run: find . -type f -name '*.sh' -print0 | xargs -0 -r -n1 sh -n
